# Generated by Django 4.1.1 on 2022-09-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_userskill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userskill',
            old_name='user_id',
            new_name='userid',
        ),
    ]
